#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

FORCE=false
if [[ "${1:-}" == "--force" ]]; then
  FORCE=true
  shift
fi

ENV_FILE="${1:-$ROOT/.env}"
USERS_FILE="$ROOT/scripts/users.intranet.json"
CREDENTIALS_FILE="$ROOT/evidence/pilot-credentials.txt"

log() {
  printf '[init-pilot-env] %s\n' "$*"
}

mkdir -p "$ROOT/evidence"

if [[ "$FORCE" != "true" && ( -f "$ENV_FILE" || -f "$USERS_FILE" ) ]]; then
  log "refusing to overwrite existing pilot files without --force"
  log "existing: ENV_FILE=$ENV_FILE USERS_FILE=$USERS_FILE"
  exit 1
fi

jwt_secret="$(openssl rand -hex 32)"
app_version="$(git rev-parse --short HEAD)"
password_reset_webhook_token="$(openssl rand -hex 24)"
owner_pass="$(openssl rand -hex 16)"
alice_pass="$(openssl rand -hex 16)"
bob_pass="$(openssl rand -hex 16)"

cat >"$USERS_FILE" <<EOF
[
  {
    "id": "u_owner",
    "name": "Team Owner",
    "role": "owner",
    "password": "${owner_pass}"
  },
  {
    "id": "u_alice",
    "name": "Alice",
    "role": "human",
    "password": "${alice_pass}"
  },
  {
    "id": "u_bob",
    "name": "Bob",
    "role": "human",
    "password": "${bob_pass}"
  }
]
EOF

cat >"$ENV_FILE" <<EOF
PORT=8080
WEB_PORT=8081
DEV_MODE=false
ALLOW_PUBLIC_REGISTER=false
STRICT_PRODUCTION_CONFIG=true
TASK_REPOSITORY_DRIVER=mongo
MONGODB_URI=mongodb://mongo:27017/?replicaSet=rs0
MONGODB_DATABASE=taskflow
JWT_SECRET=${jwt_secret}
APP_VERSION=${app_version}
BOOTSTRAP_USERS_FILE=./scripts/users.intranet.json
LOG_LEVEL=info
ACCESS_TOKEN_TTL=2h
REFRESH_TOKEN_TTL=168h
PASSWORD_RESET_TTL=1h
PASSWORD_RESET_WEBHOOK_URL=https://mailer.internal/hooks/taskflow-password-reset
PASSWORD_RESET_WEBHOOK_AUTH_TOKEN=${password_reset_webhook_token}
TRACING_ENABLED=false
TRACING_ENDPOINT=otel-collector:4318
TRACING_INSECURE=true
TRACING_SERVICE_NAME=taskflow
# Leave empty when using the bundled nginx web service (same-origin /api proxy).
CORS_ALLOWED_ORIGINS=
EOF

cat >"$CREDENTIALS_FILE" <<EOF
# Generated by scripts/init_pilot_env.sh — do not commit.
DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
APP_VERSION=${app_version}
ENV_FILE=${ENV_FILE}
BOOTSTRAP_USERS_FILE=${USERS_FILE}

u_owner / ${owner_pass}
u_alice / ${alice_pass}
u_bob / ${bob_pass}

Web entry (after: docker compose --profile full up -d --build):
  http://127.0.0.1:8081

API direct (debug):
  http://127.0.0.1:8080
EOF

chmod 600 "$CREDENTIALS_FILE" "$USERS_FILE" "$ENV_FILE"

log "wrote ${ENV_FILE}"
log "wrote ${USERS_FILE}"
log "wrote ${CREDENTIALS_FILE}"
log "validating production env"
bash scripts/validate_production_env.sh "$ENV_FILE"
log "PASS: pilot env is ready"
log "next: docker compose --env-file ${ENV_FILE} --profile full up -d --build"
